"""
All static data constants — company lists, glossary, popular stocks, levels.
Extracted from the original Streamlit app so both app.py and templates can import them.
"""

COMPANIES_BY_EXCHANGE = {
    "🇮🇳 NSE — National Stock Exchange": {
        "HDFC Bank": "HDFCBANK.NS", "ICICI Bank": "ICICIBANK.NS",
        "State Bank of India": "SBIN.NS", "Kotak Mahindra Bank": "KOTAKBANK.NS",
        "Axis Bank": "AXISBANK.NS", "IndusInd Bank": "INDUSINDBK.NS",
        "Bajaj Finance": "BAJFINANCE.NS", "Bajaj Finserv": "BAJAJFINSV.NS",
        "Bank of Baroda": "BANKBARODA.NS", "Punjab National Bank": "PNB.NS",
        "Canara Bank": "CANBK.NS", "Union Bank of India": "UNIONBANK.NS",
        "IDFC First Bank": "IDFCFIRSTB.NS", "Federal Bank": "FEDERALBNK.NS",
        "Bandhan Bank": "BANDHANBNK.NS", "AU Small Finance Bank": "AUBANK.NS",
        "Yes Bank": "YESBANK.NS", "HDFC Life Insurance": "HDFCLIFE.NS",
        "SBI Life Insurance": "SBILIFE.NS", "ICICI Lombard": "ICICIGI.NS",
        "ICICI Prudential Life": "ICICIPRULI.NS", "Shriram Finance": "SHRIRAMFIN.NS",
        "Cholamandalam Investment": "CHOLAFIN.NS", "Muthoot Finance": "MUTHOOTFIN.NS",
        "L&T Finance": "LTF.NS", "PB Fintech (PolicyBazaar)": "POLICYBZR.NS",
        "Power Finance Corporation": "PFC.NS", "REC Limited": "RECLTD.NS",
        "LIC (Life Insurance Corp)": "LICI.NS", "HDFC Asset Management": "HDFCAMC.NS",
        "Jio Financial Services": "JIOFIN.NS", "Tata Consultancy Services": "TCS.NS",
        "Infosys": "INFY.NS", "Wipro": "WIPRO.NS", "HCL Technologies": "HCLTECH.NS",
        "Tech Mahindra": "TECHM.NS", "LTIMindtree": "LTIM.NS", "Mphasis": "MPHASIS.NS",
        "Persistent Systems": "PERSISTENT.NS", "Coforge": "COFORGE.NS",
        "L&T Technology Services": "LTTS.NS", "Oracle Financial Services": "OFSS.NS",
        "Tata Elxsi": "TATAELXSI.NS", "Zensar Technologies": "ZENSARTECH.NS",
        "Sonata Software": "SONATSOFTW.NS", "Maruti Suzuki": "MARUTI.NS",
        "Tata Motors": "TATAMOTORS.NS", "Mahindra & Mahindra": "M&M.NS",
        "Eicher Motors": "EICHERMOT.NS", "Hero MotoCorp": "HEROMOTOCO.NS",
        "Bajaj Auto": "BAJAJ-AUTO.NS", "TVS Motor Company": "TVSMOTOR.NS",
        "Ashok Leyland": "ASHOKLEY.NS", "Bharat Forge": "BHARATFORG.NS",
        "Motherson Sumi (Samvardhana)": "MOTHERSON.NS", "Balkrishna Industries": "BALKRISIND.NS",
        "MRF": "MRF.NS", "Apollo Tyres": "APOLLOTYRE.NS", "Exide Industries": "EXIDEIND.NS",
        "Bosch Limited": "BOSCHLTD.NS", "Sun Pharmaceutical": "SUNPHARMA.NS",
        "Divi's Laboratories": "DIVISLAB.NS", "Dr Reddy's Laboratories": "DRREDDY.NS",
        "Cipla": "CIPLA.NS", "Lupin": "LUPIN.NS", "Aurobindo Pharma": "AUROPHARMA.NS",
        "Torrent Pharmaceuticals": "TORNTPHARM.NS", "Zydus Lifesciences": "ZYDUSLIFE.NS",
        "Mankind Pharma": "MANKIND.NS", "Alkem Laboratories": "ALKEM.NS",
        "Apollo Hospitals": "APOLLOHOSP.NS", "Max Healthcare": "MAXHEALTH.NS",
        "Fortis Healthcare": "FORTIS.NS", "Biocon": "BIOCON.NS",
        "Laurus Labs": "LAURUSLABS.NS", "Abbott India": "ABBOTINDIA.NS",
        "Pfizer India": "PFIZER.NS", "Glenmark Pharmaceuticals": "GLENMARK.NS",
        "ITC": "ITC.NS", "Hindustan Unilever": "HINDUNILVR.NS",
        "Nestle India": "NESTLEIND.NS", "Britannia Industries": "BRITANNIA.NS",
        "Tata Consumer Products": "TATACONSUM.NS", "Dabur India": "DABUR.NS",
        "Marico": "MARICO.NS", "Godrej Consumer Products": "GODREJCP.NS",
        "Colgate-Palmolive India": "COLPAL.NS", "United Spirits": "MCDOWELL-N.NS",
        "United Breweries": "UBL.NS", "Varun Beverages": "VBL.NS",
        "Emami": "EMAMILTD.NS", "Procter & Gamble Hygiene": "PGHH.NS",
        "Jubilant FoodWorks": "JUBLFOOD.NS", "Trent": "TRENT.NS",
        "Avenue Supermarts (DMart)": "DMART.NS", "Titan Company": "TITAN.NS",
        "Asian Paints": "ASIANPAINT.NS", "Berger Paints": "BERGEPAINT.NS",
        "Pidilite Industries": "PIDILITIND.NS", "Havells India": "HAVELLS.NS",
        "Voltas": "VOLTAS.NS", "Crompton Greaves Consumer": "CROMPTON.NS",
        "Blue Star": "BLUESTARCO.NS", "Zomato": "ZOMATO.NS",
        "Paytm (One97 Communications)": "PAYTM.NS", "Nykaa (FSN E-Commerce)": "NYKAA.NS",
        "IRCTC": "IRCTC.NS", "Delhivery": "DELHIVERY.NS",
        "Reliance Industries": "RELIANCE.NS", "Adani Enterprises": "ADANIENT.NS",
        "Adani Ports": "ADANIPORTS.NS", "Adani Power": "ADANIPOWER.NS",
        "Adani Green Energy": "ADANIGREEN.NS", "Adani Total Gas": "ATGL.NS",
        "Power Grid Corporation": "POWERGRID.NS", "NTPC": "NTPC.NS",
        "ONGC": "ONGC.NS", "Coal India": "COALINDIA.NS",
        "Indian Oil Corporation": "IOC.NS", "Bharat Petroleum (BPCL)": "BPCL.NS",
        "Hindustan Petroleum (HPCL)": "HINDPETRO.NS", "GAIL India": "GAIL.NS",
        "Tata Power": "TATAPOWER.NS", "Larsen & Toubro": "LT.NS",
        "Siemens India": "SIEMENS.NS", "ABB India": "ABB.NS",
        "Tata Steel": "TATASTEEL.NS", "JSW Steel": "JSWSTEEL.NS",
        "Hindalco Industries": "HINDALCO.NS", "Vedanta": "VEDL.NS",
        "UltraTech Cement": "ULTRACEMCO.NS", "Shree Cement": "SHREECEM.NS",
        "Ambuja Cements": "AMBUJACEM.NS", "ACC Limited": "ACC.NS",
        "Grasim Industries": "GRASIM.NS", "Bharti Airtel": "BHARTIARTL.NS",
        "Vodafone Idea": "IDEA.NS", "Bharat Electronics": "BEL.NS",
        "Hindustan Aeronautics": "HAL.NS", "Bharat Heavy Electricals": "BHEL.NS",
        "Polycab India": "POLYCAB.NS", "Dixon Technologies": "DIXON.NS",
        "DLF": "DLF.NS", "Godrej Properties": "GODREJPROP.NS",
        "Oberoi Realty": "OBEROIRLTY.NS", "Prestige Estates": "PRESTIGE.NS",
        "Macrotech Developers (Lodha)": "LODHA.NS", "Info Edge (Naukri)": "NAUKRI.NS",
        "InterGlobe Aviation (IndiGo)": "INDIGO.NS",
    },
    "🇮🇳 BSE — Bombay Stock Exchange": {
        "Bank of Baroda": "BANKBARODA.BO", "Punjab National Bank": "PNB.BO",
        "Union Bank of India": "UNIONBANK.BO", "Canara Bank": "CANBK.BO",
        "Yes Bank": "YESBANK.BO", "Tata Power": "TATAPOWER.BO",
        "Suzlon Energy": "SUZLON.BO", "Vodafone Idea": "IDEA.BO",
        "Bharat Heavy Electricals": "BHEL.BO", "Steel Authority of India": "SAIL.BO",
        "Reliance Power": "RPOWER.BO",
    },
    "🇺🇸 NYSE / NASDAQ": {
        "Apple": "AAPL", "Microsoft": "MSFT", "Amazon": "AMZN",
        "Alphabet (Google)": "GOOGL", "Meta (Facebook)": "META",
        "Tesla": "TSLA", "NVIDIA": "NVDA", "JPMorgan Chase": "JPM",
        "Johnson & Johnson": "JNJ", "Visa": "V", "Mastercard": "MA",
        "Procter & Gamble": "PG", "Walmart": "WMT", "Disney": "DIS",
        "Netflix": "NFLX", "Goldman Sachs": "GS", "BlackRock": "BLK",
        "ExxonMobil": "XOM", "Coca Cola": "KO", "Nike": "NKE",
        "McDonald's": "MCD", "AMD": "AMD", "Salesforce": "CRM",
        "Adobe": "ADBE", "PayPal": "PYPL", "Uber": "UBER",
        "Airbnb": "ABNB", "Palantir": "PLTR", "Berkshire Hathaway": "BRK-B",
        "Intel": "INTC", "Spotify": "SPOT", "Snowflake": "SNOW",
    },
}

ALL_COMPANIES = {
    name: ticker
    for ex in COMPANIES_BY_EXCHANGE.values()
    for name, ticker in ex.items()
}

POPULAR = {
    "Reliance Industries": "RELIANCE.NS",
    "HDFC Bank":           "HDFCBANK.NS",
    "Infosys":             "INFY.NS",
    "Tata Motors":         "TATAMOTORS.NS",
    "Tesla":               "TSLA",
    "NVIDIA":              "NVDA",
    "Apple":               "AAPL",
    "Zomato":              "ZOMATO.NS",
}

KNOWLEDGE_LEVELS = {
    "🌱 Beginner":     "Never invested before or just getting started",
    "📈 Learner":      "Know the basics, still learning",
    "💼 Intermediate": "Comfortable with P/E, ROE and basic analysis",
    "🏦 Expert":       "Deep market knowledge, technical analysis",
}

GLOSSARY = {
    "P/E Ratio":        "Price to Earnings — how much you pay for every ₹1 of profit. Lower = potentially cheaper.",
    "Forward P/E":      "Expected P/E based on next year's estimated earnings. Lower than trailing P/E = earnings expected to grow.",
    "P/B Ratio":        "Price to Book — stock price vs net assets. Below 1 means trading below book value.",
    "EPS":              "Earnings Per Share — company profit divided by number of shares. Higher is better.",
    "EV/EBITDA":        "Enterprise Value to EBITDA — accounts for debt in valuation. Popular for comparing companies.",
    "ROE":              "Return on Equity — profit generated per rupee of shareholder money. Above 15% is generally good.",
    "ROA":              "Return on Assets — how efficiently all assets are used to generate profit.",
    "Debt to Equity":   "How much the company has borrowed vs what shareholders own. D/E below 50% is generally low.",
    "Profit Margin":    "% of revenue that becomes profit. Higher = more efficient business model.",
    "Gross Margin":     "Revenue minus cost of goods sold, as a %. High gross margin = strong pricing power.",
    "Operating Margin": "Profit after operating costs. Shows how efficient the core business is.",
    "Free Cash Flow":   "Cash left after all expenses and investments. Positive FCF = real cash being generated.",
    "Current Ratio":    "Current assets / current liabilities. Above 1 = can pay short-term obligations.",
    "Beta":             "How much the stock moves vs the market. Beta 1.5 = 50% more volatile than Nifty/S&P 500.",
    "Revenue Growth":   "How much sales grew year-on-year. Above 10% is healthy for most sectors.",
    "Market Cap":       "Total value of all shares. Large cap >₹20,000 Cr, mid cap ₹5,000–20,000 Cr.",
    "52 Week High/Low": "Highest and lowest price in the past year. Useful for understanding price range.",
    "Moving Average":   "Average price over a period. MA50 = last 50 days. Price above MA200 = positive trend.",
    "Volatility":       "How much the price moves daily. Higher = more risk and potential reward.",
    "Dividend Yield":   "Annual dividend as % of stock price. Good for income-seeking investors.",
    "Bull Market":      "Rising market — prices going up over a sustained period.",
    "Bear Market":      "Falling market — prices going down over a sustained period.",
    "NSE":              "National Stock Exchange — India's largest exchange by trading volume.",
    "BSE":              "Bombay Stock Exchange — oldest exchange in Asia.",
    "SEBI":             "Securities and Exchange Board of India — regulates Indian markets.",
    "FII":              "Foreign Institutional Investors — large foreign funds investing in Indian markets.",
    "DII":              "Domestic Institutional Investors — Indian mutual funds and insurance companies.",
}
